#!/usr/bin/env python

"""
A script to generate a file named index.html from sheet.md and templace.html
"""

from bs4 import BeautifulSoup
import markdown
import subprocess


top = """
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="UTF-8">
    <title>Scientific python cheat sheet by IPGP</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.5">
    <link rel="stylesheet" type="text/css" href="stylesheets/normalize.css" media="screen">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="stylesheets/stylesheet.css" media="screen">
    <link rel="stylesheet" type="text/css" href="stylesheets/github-light.css" media="screen">
  </head>
  <body>
    <section class="main-content">
"""

bottom = """
      <footer class="site-footer">
        <span class="site-footer-owner"><a href="https://github.com/IPGP/scientific_python_cheat_sheet">Scientific python cheat sheet</a> is maintained by <a href="https://github.com/IPGP">IPGP</a>.</span>

        <span class="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using the <a href="https://github.com/jasonlong/cayman-theme">Cayman theme</a> by <a href="https://twitter.com/jasonlong">Jason Long</a>.</span>
      </footer>

    </section>
  </body>
</html>
"""

input_file = "sheet.md"
output_file = "sheet.html"
hightight_style = "pygment"

try:
    cmd = "pandoc {} -s -o --highlight-style } {} {}".format(input_file,
                                                             hightight_style,
                                                             output_file)
    print cmd
    subprocess.call(cmd, shell=True)
    soup_sheet = BeautifulSoup(open(output_file), "html.parser")
    list_html = map(str, list(soup_sheet.body.children))
    sheet_html = ''.join(list_html)
    print "went the pandoc way"
except:
    print "pandoc failed, using shitty markdown"
    with open(input_file, "r") as f:
        text = f.read()
    sheet_html = markdown.markdown(text)

sheet_html_lines = sheet_html.split("\n")
f = open("index.html", "w")
flag_first_h2 = False
f.write(top+"\n")
for line in sheet_html_lines:
    if "markdown-toc" in line:
        continue

    if "h2" in line:
        if flag_first_h2:
            f.write("</div>\n<div class=group>\n")
            f.write(line+"\n")
        else:
            f.write("<div class=group>\n")
            f.write(line+"\n")
            flag_first_h2 = True
    else:
        f.write(line+"\n")

f.write("</div>\n")
f.write(bottom+"\n")
f.close()
